name: Build and Push Next.js Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.BUILD_TOKEN }}

    - name: Build and push Next.js image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/nextjs-app:latest .
        docker push ghcr.io/${{ github.repository_owner }}/nextjs-app:latest
